/*
 * IMPORTANT:
 * This code has been automatically generated by a tool.
 * Any modifications to this code will not be kept.
 * 
 * This file was last generated at {datetime}
 */

using System.Collections.Generic;
using System.Text.RegularExpressions;

[assembly: System.CLSCompliant(true)]
